### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by michrawson** [tdavislab/Hypergraph-Vis#1]
Failed to run. See below.

LOG:

$ python3 run.py 
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/home/rawson/source/Hypergraph-Vis/app/__init__.py", line 12, in <module>
    from .util import assets
  File "/home/rawson/source/Hypergraph-Vis/app/util/assets.py", line 2, in <module>
    from flask_assets import Bundle, Environment
ModuleNotFoundError: No module named 'flask_assets'

$ python3 -m flask run.py 
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/home/rawson/.local/lib/python3.8/site-packages/flask/cli.py", line 260, in locate_app
    __import__(module_name)
  File "/home/rawson/source/Hypergraph-Vis/app/__init__.py", line 12, in <module>
    from .util import assets
  File "/home/rawson/source/Hypergraph-Vis/app/util/assets.py", line 2, in <module>
    from flask_assets import Bundle, Environment
ModuleNotFoundError: No module named 'flask_assets'

Usage: python -m flask [OPTIONS] COMMAND [ARGS]...
Try 'python -m flask --help' for help.

Error: No such command 'run.py'.

**Comment by zhou325** [comment]
Hi Michael,

It seems you need to install the python library 'flask_assets' using the command 'pip install flask_assets'.
Thank you for letting us know. I have updated the installation instruction.
Please let me know if it doesn't work.

Best,
Youjia

**Comment by michrawson** [comment]
That fixed it, thanks!
